### ISSUE TITLE
Price range filter has repeated, unclear options

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#369]
The price range filter is way off: 
https://d3lnoy3aplwg2k.cloudfront.net/Tools
![image](https://user-images.githubusercontent.com/72166715/176543530-cc699ae4-afed-4435-97d9-409e4d7dfd96.png)

Was previously logical breaks in units like `<10`, `10-25`, `25-50`, etc

**Comment by masonmcelvain** [comment]
Yes, that seems like it! Using the bucketer instead should fix the problem

**Comment by dhmacs** [comment]
@davidrans this still seems not fixed after the PR got merged, any clue?

**Comment by davidrans** [comment]
I'll take a look
