### ISSUE TITLE
Redirect some more Product List tags 

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#529]
https://github.com/iFixit/react-commerce/pull/524 was done, but there are others trickling in that weren't caught.

List:
| example old collection path | ifixit redirect | next redirect | non-existent item type |
| -- | -- | -- | -- |
| /Store/iPad/iPad-Pro/USB_Boards | /Parts/iPad_Pro/USB_Boards | /Parts/iPad_Pro/Boards | Boards |
| /Store/iPad/iPad-Pro/Gripping | /Parts/iPad_Pro/Gripping | none | Gripping |
| /Store/iPad/iPad-Pro/Prying_and_Opening | /Parts/iPad_Pro/Prying_and_Opening | none | Prying_and_Opening |
| /Store/iPad/iPad-Pro/Sensors | /Parts/iPad_Pro/Sensors | none | Sensors |
| *️⃣ /Store/Game-Console/Sony-Game-Consoles/I | /Parts/Sony_Game_Console/I | none | I |
| /Store/Game-Console/PlayStation-5/Optical_Drives | /Parts/PlayStation_5/Optical_Drives | none | Optical_Drives |
| /Store/Game-Console/Steam-Deck/Power_Supplies | /Parts/Steam_Deck/Power_Supplies | none | Power_Supplies |

*️⃣  - redirected from `/Store/Game-Console/Sony-Game-Consoles/I/O_Board` which was already broken on the old pages

CC: @ifixitmaxb @davidrans

**Comment by erinemay** [comment]
I'm poking through some old collections a little more thoroughly now. Updating that table as I find problematic item types.

**Comment by ifixitmaxb** [comment]
These legacy Collections still redirect to a /Logic_Boards Item Type and they should be redirecting to /Motherboards:
https://www.ifixit.com/Store/iPad/iPad/Logic_Boards
https://www.ifixit.com/Store/iPad/iPad-Air/Logic_Boards
https://www.ifixit.com/Store/iPad/iPad-Air-2/Logic_Boards
https://www.ifixit.com/Store/iPad/iPad-Pro/Logic_Boards
https://www.ifixit.com/Store/iPad/iPad-Pro-12.9”/Logic_Boards
https://www.ifixit.com/Store/iPhone/iPhone/Logic_Boards
https://www.ifixit.com/Store/iPhone/iPhone-6s/Logic_Boards
https://www.ifixit.com/Store/iPhone/iPhone-7/Logic_Boards
https://www.ifixit.com/Store/iPhone/iPhone-7-Plus/Logic_Boards
https://www.ifixit.com/Store/iPhone/iPhone-XS/Logic_Boards
https://www.ifixit.com/Store/iPhone/iPhone-XS-Max-A1921/Logic_Boards
https://www.ifixit.com/Store/Mac/iMac/Logic_Boards
https://www.ifixit.com/Store/Mac/iMac-Intel-27”/Logic_Boards
https://www.ifixit.com/Store/Mac/MacBook-Air/Logic_Boards
https://www.ifixit.com/Store/Mac/MacBook-Air-11”-Model-A1465/Logic_Boards
https://www.ifixit.com/Store/Mac/MacBook-Air-13”/Logic_Boards
https://www.ifixit.com/Store/Mac/MacBook-Air-13”-2018/Logic_Boards
https://www.ifixit.com/Store/Mac/MacBook-Air-13”-Early-2020/Logic_Boards
https://www.ifixit.com/Store/Mac/MacBook-Air-13”-Model-A1369/Logic_Boards
https://www.ifixit.com/Store/Mac/MacBook-Air-13”-Model-A1466/Logic_Boards
https://www.ifixit.com/Store/Mac/MacBook-Pro/Logic_Boards
https://www.ifixit.com/Store/Mac/MacBook-Pro-13”-Retina/Logic_Boards
https://www.ifixit.com/Store/Mac/MacBook-Pro-13”-Retina-Early-2015/Logic_Boards
https://www.ifixit.com/Store/Mac/MacBook-Pro-13”-Retina-Late-2013/Logic_Boards
https://www.ifixit.com/Store/Mac/MacBook-Pro-13”-Retina-Mid-2014/Logic_Boards
https://www.ifixit.com/Store/Mac/MacBook-Pro-13”-Touch-Bar-Late-2016/Logic_Boards
https://www.ifixit.com/Store/Mac/MacBook-Pro-13”-Touch-Bar-Mid-2017/Logic_Boards
https://www.ifixit.com/Store/Mac/MacBook-Pro-15”-Touch-Bar-2019/Logic_Boards
https://www.ifixit.com/Store/Mac/MacBook-Pro-15”-Touch-Bar-Late-2016/Logic_Boards
https://www.ifixit.com/Store/Mac/MacBook-Pro-15”-Touch-Bar-Mid-2017/Logic_Boards
https://www.ifixit.com/Store/Mac/MacBook-Pro-15”-Touch-Bar-Mid-2018/Logic_Boards
https://www.ifixit.com/Store/Mac/MacBook-Pro-16”-2019/Logic_Boards
https://www.ifixit.com/Store/Mac/Mac-mini/Logic_Boards
https://www.ifixit.com/Store/Mac/Mac-mini-Model-A1347/Logic_Boards

**Comment by ifixitmaxb** [comment]
This might be related: https://github.com/iFixit/react-commerce/issues/542

**Comment by ifixitmaxb** [comment]
Where I'm still seeing this behavior of multiple hops from legacy Item Type to new Item Type:
/Adhesive_Strips --> /Adhesives
/Hard_Drives_(SATA) --> /Hard_Drives
/Lightning_Connector --> /Cables
/Logic_Boards --> /Motherboards
/Rubber_Feet --> /Case_Components
/Upgrade_Kits --> /Hard_Drives

When I load the legacy Item Types in my browser, I get no results, but if I refresh again, I get sent to the proper page.

**Comment by davidrans** [comment]
> When I load the legacy Item Types in my browser, I get no results, but if I refresh again, I get sent to the proper page.

I'm not seeing that same behavior in Chrome. Is there a link where you're consistently getting that behavior @ifixitmaxb?

**Comment by ifixitmaxb** [comment]
Try these: 
https://www.ifixit.com/Parts/iPhone_11/Adhesive%20Strips
https://www.ifixit.com/Parts/iPhone_XS/Lightning%20Connector
https://www.ifixit.com/Parts/PlayStation_5/Optical%20Drives
https://www.ifixit.com/Parts/Steam_Deck/Power%20Supplies
https://www.ifixit.com/Parts/MacBook_Pro/Rubber%20Feet

Here is a recording of some examples:
https://www.loom.com/share/33d42f825c4e44c68a08f74294e15b68

**Comment by erinemay** [comment]
Moving this here from https://github.com/iFixit/react-commerce/pull/565 since that pr is only dealing with a few old collection types that don't map to new item types.

Problem: Some item types from old collections redirect to a new item type and some do not:

> https://www.ifixit.com/Store/Game-Console/Xbox-One/Power_Supplies redirects to https://www.ifixit.com/Parts/Xbox_One/Power_Supplies which exists and contains the same products as the legacy collection.
> 
> https://www.ifixit.com/Store/Game-Console/Steam-Deck/Power_Supplies redirects to https://www.ifixit.com/Parts/Steam_Deck/Power_Supplies which doesn't exist (no Power_Supplies item type in this collection). And all the products that were under that legacy collection are under https://www.ifixit.com/Parts/Steam_Deck/Power_Adapters.

**Comment by sterlinghirsh** [comment]
@davidrans Is this done? Are there remaining redirects to implement?

**Comment by davidrans** [comment]
I don't know if I fixed all the URLs in this issue. Is it too late for it to be useful to add more redirects @ifixitmaxb ?

**Comment by ifixitmaxb** [comment]
It seems like we're still not handling /SSD_Enclosures properly - it seems like we need to 301 all /SSD_Enclosures to /Hard_Drives. See this thread: https://ifixit.slack.com/archives/C02KMFEHX62/p1662503218560739

Same with /Hard_Drives_(SATA) - it seems like we didn't 301 in all cases to /Hard_Drives - I only have a few examples but here's one, https://www.ifixit.com/Store/Mac/Mac-mini-Model-A1347/Hard_Drives_(SATA) seems to 308 to /Hard_Drives.

**Comment by danielcliu-ifixit** [comment]
@ifixitmaxb Im not able to replicate any issues on this
> Same with /Hard_Drives_(SATA) - it seems like we didn't 301 in all cases to /Hard_Drives - I only have a few examples but here's one, https://www.ifixit.com/Store/Mac/Mac-mini-Model-A1347/Hard_Drives_(SATA) seems to 308 to /Hard_Drives. 

please provide instances where its bugged if this is still an issue

**Comment by danielcliu-ifixit** [comment]
I've addressed every clear redirect i can find at this point, but this issue has become a bit directionless and hard to sift through. Im going to close this now and if any other redirects are desired please create a new issue and we'll deal with it from there.
